### ISSUE TITLE
PHP Fatal error when a product has an availability date in the future

### ISSUE THREAD

**Issue by torvista** [lat9/gpsf#14]
https://github.com/lat9/gpsf/blob/5b23df84745fb3db16c7acf4b3cd9f340f7b3b45/includes/classes/gpsfFeedGenerator.php#L803
it seems this should be 
`            $this->xmlWriter->writeElement('g:availability_date', date('Y-m-d', strtotime($product['products_date_available'] . 'T00:00:00')));`

**Comment by lat9** [comment]
I'm confused, that's how that line reads currently.  `strtotime` returns an `int` and the code section prior to that line has verified that the `products_date_available` isn't null.

**Comment by torvista** [comment]
. 'T00:00:00' is **appended** to the strtotime result instead of being part of it's parameter.

**Comment by torvista** [comment]
Wrong again, the 'T00:00:00' should be appended to the result of date.

**Comment by drbyte** [comment]
Google is big on using standardized RFC formats for things. Is there already a compliant RFC date/time string format in PHP's supported formats? Why not use that instead of hacking things together manually?

**Comment by torvista** [comment]
Again, when a future date is set:
> PHP Fatal error:  Uncaught TypeError: date(): Argument #2 ($timestamp) must be of type ?int, bool given in ...\includes\classes\gpsfFeedGenerator.php:791
> Stack trace:
> #0 ...\includes\classes\gpsfFeedGenerator.php(791): date('c', false

from
https://github.com/lat9/gpsf/blob/b9292604f51bc7b0d7441eefc6fa5e987c447cee/includes/classes/gpsfFeedGenerator.php#L791

as the value passed to strtotime is eg:
2024-03-20 00:00:00 00:00:00 

which returns false.

**Comment by lat9** [comment]
@torvista, next time, please open a new issue referencing a closed one; otherwise, I'm sure to miss the update!
