### ISSUE TITLE
Suggestion: exclusion of some products from the feed generation

### ISSUE THREAD

**Issue by torvista** [lat9/gpsf#17]
...to make the skipped products list into a real-errors only/fix-me list...

A simple text skip-list would do.

But since all products should have a google category assigned: that is a new database field per product (in my setup).
Perhaps a specific string ("xxx") in this field could make it a skipped product?
Just ideas...

**Comment by torvista** [comment]
I see there's all sorts of voodoo in \classes\gpsf\gpsfBase.php
for such things

**Comment by lat9** [comment]
Yea, I should add an example to the Wiki to show some basic processing like that.

**Comment by lat9** [comment]
At a minimum, there's now that Wiki link in the repo's base readme.md.
