### ISSUE TITLE
$extension_custom_fields['link'] is added, not replaced

### ISSUE THREAD

**Issue by torvista** [lat9/gpsf#22]
Since I'm using a url rewriter, the default <link> generated url is static (www.website.com/widgets/main_widget) and language-dependant.
I was looking at using the native url instead.

(I've already added an extra parameter to zen_href_link to prevent url-rewriting when not required.)

But, when trying to replace the default <link> tag by $extension_custom_fields['link'], it is added to the xml instead of replacing the default <link> tag.

**Comment by lat9** [comment]
Noting that this change will also address #11.

**Comment by torvista** [comment]
ok. 

I'm of the view that a static url may change through changes in the site, but the native url will always "get" to the product even if  it is moved (as long as the pid stays the same). Same idea for a sitemap...
Opinions from the SEO experts?

**Comment by lat9** [comment]
> ok.
> 
> I'm of the view that a static url may change through changes in the site, but the native url will always "get" to the product even if it is moved (as long as the pid stays the same). Same idea for a sitemap... Opinions from the SEO experts?

Don't know if any "SEO experts" are watching.
