### ISSUE TITLE
suggestion: show elapsed/processing time on a failure/timeout

### ISSUE THREAD

**Issue by torvista** [lat9/gpsf#24]
Useful as a pointer to which php/server parameter is timing-out.

**Comment by lat9** [comment]
I'm not sure what you're looking for here, an example would help.

**Comment by torvista** [comment]
![image](https://github.com/lat9/gpsf/assets/4391026/ac141019-fe88-4262-93ab-dae2a77a142a)

If debugging a timeout, that could take a couple of minutes...and if you're not watching the screen constantly (yawn), you don't know **when** it timed out. An indication of elapsed time would be a hint as to where the limit may be defined (if it fails at 30, 60, 90 etc.).
