### ISSUE TITLE
Shipping costs per country served

### ISSUE THREAD

**Issue by torvista** [lat9/gpsf#35]
Feasible to get the cheapest quote from the shipping modules?
Here's what I hard-coded previously/was accepted.

> <g:shipping>
>         <g:country>ES</g:country>
>         <g:service>SEUR 24</g:service>
>         <g:price>0 EUR</g:price>
>         <g:min_handling_time>1</g:min_handling_time>
>         <g:max_handling_time>2</g:max_handling_time>
>         <g:min_transit_time>1</g:min_transit_time>
>         <g:max_transit_time>2</g:max_transit_time>
> </g:shipping>

**Comment by torvista** [comment]
Maybe hard-coding it is better....as long as it gets validated by GMC, it doesn't need to be accurate.

**Comment by torvista** [comment]
I'll note this email from the Merchant centre.
 
> Starting from 31 July 2024, providing delivery cost information will be  mandatory for your products to be approved and displayed on Google,  including Shopping ads and free listings in India and New Zealand. | Starting from 31 July 2024, providing delivery cost information will be  mandatory for your products to be approved and displayed on Google,  including Shopping ads and free listings in India and New Zealand.
> Starting from 31 July 2024, providing delivery cost information will be  mandatory for your products to be approved and displayed on Google,  including Shopping ads and free listings in India and New Zealand.

**Comment by lat9** [comment]
Sounds like a good application for the GPSF extensions.

**Comment by torvista** [comment]
>would not necessarily be valid for a cart that includes multiple products

I think this is just about keeping the feed valid as far as Google is concerned, but not necessarily accurate! If someone gets as far as putting items in the cart that's almost job done.

If timeouts are a problem, is it an option to generate a feed then parse that file to add the shipping as a separate operation?
