### ISSUE TITLE
$_REQUEST['key'] contains "DirectMap1G"

### ISSUE THREAD

**Issue by torvista** [lat9/gpsf#43]
I've just moved my shop to Jeandret and when checking GPSF I got "Incorrect key supplied!"

And I find that $key contains "DirectMap1G" instead of being empty!

So, not sure where the issue lies but there it is.

**Comment by dbltoe** [comment]
WAG
When looking at https://unix.stackexchange.com/questions/605142/what-is-using-a-1g-byte-page-on-my-system, I wonder if it might have been a carryover from the previous host's attempt at large file operations.

**Comment by torvista** [comment]
I don't have that text anywhere.

**Comment by lat9** [comment]
What value is in the GPSF configuration?

**Comment by torvista** [comment]
>What value is in the GPSF configuration?

Nothing.

I outputted the key and constant:
![image](https://github.com/user-attachments/assets/31ec3888-b5ac-4a24-9bb3-0ffe8ccbd397)

**Comment by lat9** [comment]
That makes no sense to me.

**Comment by lat9** [comment]
If you set the access-key to a non-blank value, does it get overwritten?

**Comment by torvista** [comment]
With a string in the access key:
![image](https://github.com/user-attachments/assets/24078f57-a1ef-4366-bc13-1207d823436a)

no string in access key

![image](https://github.com/user-attachments/assets/3029165f-8fac-48f1-b189-c9bf053bfe2b)

**Comment by lat9** [comment]
Interesting, although it's not something that GPSF2 has control over.

**Comment by torvista** [comment]
My bad. I have extra server info in the header (including memory info) and that was using $key...and this is after the unset($key) in gpsf so was getting auto-substituted for the empty value.
